# Generated by Django 4.2.4 on 2023-09-14 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employees',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
